algoritmo "semnome"
// Função :
// Autor :
// Data : 02/03/2021
// Seção de Declarações 
var
      numero,limite:inteiro
inicio
// Seção de Comandos 
             numero <- 1
             limite <- 10
             Escreva("Digite um numero: ")
             leia(numero)
             Enquanto numero <= limite faca
             Escreval("contagem igual:",numero)
             numero <- numero + 1;
             fimEnquanto
                  
fimalgoritmo
